// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusManagement.Models;

public partial class Bus
{
    public int BusID { get; set; }

    public int? BusNo { get; set; }

    public string BusRoute { get; set; }

    public string Descripton { get; set; }
}