// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BranchTrainee1.Models;

public partial class Branch
{
    [Key]
    public int BranchID { get; set; }

    public string BranchName { get; set; }

    public string Description { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<Trainee> Trainees { get; set; } = new List<Trainee>();
}