// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BranchTrainee1.Models;

[Table("Trainee")]
public partial class Trainee
{
    [Key]
    public int TraineeID { get; set; }

    public int? BranchID { get; set; }

    public string TraineeName { get; set; }

    public string Location { get; set; }

    public string Description { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("Trainees")]
    public virtual Branch Branch { get; set; }
}